set -gx COLOR_BG          "#282828"
set -gx COLOR_BG_HARD     "#1d2021"
set -gx COLOR_BG_SOFT     "#32302f"
set -gx COLOR_FG          "#ebdbb2"
set -gx COLOR_FG_DIM      "#d5c4a1"

set -gx COLOR_RED         "#cc241d"
set -gx COLOR_RED_BRIGHT  "#fb4934"
set -gx COLOR_GREEN       "#98971a"
set -gx COLOR_GREEN_BRIGHT "#b8bb26"
set -gx COLOR_YELLOW      "#d79921"
set -gx COLOR_YELLOW_BRIGHT "#fabd2f"
set -gx COLOR_BLUE        "#458588"
set -gx COLOR_BLUE_BRIGHT "#83a598"
set -gx COLOR_PURPLE      "#b16286"
set -gx COLOR_PURPLE_BRIGHT "#d3869b"
set -gx COLOR_AQUA        "#689d6a"
set -gx COLOR_AQUA_BRIGHT "#8ec07c"
set -gx COLOR_ORANGE      "#d65d0e"
set -gx COLOR_ORANGE_BRIGHT "#fe8019"

set -gx COLOR_SURFACE     "#3c3836"
set -gx COLOR_OVERLAY     "#504945"
set -gx COLOR_MUTED       "#665c54"

set -gx COLOR_ACCENT      "#d79921"
set -gx COLOR_BORDER      "#d65d0e"

set -gx GTK_THEME         "gruvbox-dark-gtk"
set -gx ICON_THEME        "Gruvbox-Plus-Dark"
set -gx CURSOR_THEME      "Simp1e-Gruvbox-Dark"
set -gx GTK_FONT          "Adwaita Sans Light 11"

set -gx CMATRIX_COLOR     "red"
