set -gx COLOR_BG          "#1e1e2e"
set -gx COLOR_BG_HARD     "#11111b"
set -gx COLOR_BG_SOFT     "#181825"
set -gx COLOR_FG          "#cdd6f4"
set -gx COLOR_FG_DIM      "#bac2de"

set -gx COLOR_RED         "#f38ba8"
set -gx COLOR_RED_BRIGHT  "#f38ba8"
set -gx COLOR_GREEN       "#a6e3a1"
set -gx COLOR_GREEN_BRIGHT "#a6e3a1"
set -gx COLOR_YELLOW      "#f9e2af"
set -gx COLOR_YELLOW_BRIGHT "#f9e2af"
set -gx COLOR_BLUE        "#89b4fa"
set -gx COLOR_BLUE_BRIGHT "#89b4fa"
set -gx COLOR_PURPLE      "#cba6f7"
set -gx COLOR_PURPLE_BRIGHT "#cba6f7"
set -gx COLOR_AQUA        "#94e2d5"
set -gx COLOR_AQUA_BRIGHT "#94e2d5"
set -gx COLOR_ORANGE      "#fab387"
set -gx COLOR_ORANGE_BRIGHT "#fab387"

set -gx COLOR_SURFACE     "#313244"
set -gx COLOR_OVERLAY     "#45475a"
set -gx COLOR_MUTED       "#585b70"

set -gx COLOR_ACCENT      "#cba6f7"
set -gx COLOR_BORDER      "#94e2d5"

set -gx GTK_THEME         "catppuccin-mocha-blue-standard+default"
set -gx ICON_THEME        "Papirus-Dark"
set -gx CURSOR_THEME      "Catppuccin Mocha Mauve"
set -gx GTK_FONT          "Adwaita Sans Light 11"

set -gx CMATRIX_COLOR     "magenta"
