$bg       = rgb(282828)
$bg1      = rgb(3c3836)
$bg2      = rgb(504945)
$fg       = rgb(ebdbb2)

$red      = rgb(fb4934)
$orange   = rgb(fe8019)
$yellow   = rgb(fabd2f)
$green    = rgb(b8bb26)
$blue     = rgb(83a598)
$purple   = rgb(d3869b)
$aqua     = rgb(8ec07c)

$accent   = rgb(d79921)
$border   = rgb(d65d0e)

$shadowAlpha = 282828
