$bg       = rgb(2e3440)
$bg1      = rgb(434c5e)
$bg2      = rgb(4c566a)
$fg       = rgb(e5e9f0)

$red      = rgb(bf616a)
$orange   = rgb(d08770)
$yellow   = rgb(ebcb8b)
$green    = rgb(a3be8c)
$blue     = rgb(81a1c1)
$purple   = rgb(b48ead)
$aqua     = rgb(8fbcbb)

$accent   = rgb(81a1c1)
$border   = rgb(8fbcbb)

$shadowAlpha = 2e3440
