$bg       = rgb(1e1e2e)
$bg1      = rgb(313244)
$bg2      = rgb(45475a)
$fg       = rgb(cdd6f4)

$red      = rgb(f38ba8)
$orange   = rgb(fab387)
$yellow   = rgb(f9e2af)
$green    = rgb(a6e3a1)
$blue     = rgb(89b4fa)
$purple   = rgb(cba6f7)
$aqua     = rgb(94e2d5)

$accent   = rgb(cba6f7)
$border   = rgb(94e2d5)

$shadowAlpha = 1e1e2e
