$config_path = ~/.config/hypr/config

source = $config_path/hyprland-visual.conf


################
### MONITORS ###
################

source = $config_path/monitors_setup.conf

###################
### MY PROGRAMS ###
###################

source = $config_path/program_binding.conf

#################
### AUTOSTART ###
#################

source = $config_path/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = $config_path/env_vars.conf

#############
### INPUT ###
#############

source = $config_path/input.conf

###################
### KEYBINDINGS ###
###################

source = $config_path/keybindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = $config_path/windows_and_workspaces.conf
