set -gx COLOR_BG          "#2e3440"
set -gx COLOR_BG_HARD     "#1d2021"
set -gx COLOR_BG_SOFT     "#3b4252"
set -gx COLOR_FG          "#e5e9f0"
set -gx COLOR_FG_DIM      "#d8dee9"

set -gx COLOR_RED         "#bf616a"
set -gx COLOR_RED_BRIGHT  "#bf616a"
set -gx COLOR_GREEN       "#a3be8c"
set -gx COLOR_GREEN_BRIGHT "#a3be8c"
set -gx COLOR_YELLOW      "#ebcb8b"
set -gx COLOR_YELLOW_BRIGHT "#ebcb8b"
set -gx COLOR_BLUE        "#81a1c1"
set -gx COLOR_BLUE_BRIGHT "#81a1c1"
set -gx COLOR_PURPLE      "#b48ead"
set -gx COLOR_PURPLE_BRIGHT "#b48ead"
set -gx COLOR_AQUA        "#8fbcbb"
set -gx COLOR_AQUA_BRIGHT "#8fbcbb"
set -gx COLOR_ORANGE      "#d08770"
set -gx COLOR_ORANGE_BRIGHT "#d08770"

set -gx COLOR_SURFACE     "#434c5e"
set -gx COLOR_OVERLAY     "#4c566a"
set -gx COLOR_MUTED       "#4c566a"

set -gx COLOR_ACCENT      "#81a1c1"
set -gx COLOR_BORDER      "#8fbcbb"

set -gx GTK_THEME         "Nordic"
set -gx ICON_THEME        "Nordzy"
set -gx CURSOR_THEME      "Nordzy-cursors"
set -gx GTK_FONT          "Adwaita Sans Light 11"
