workspace=1, monitor:LVDS-1
workspace=2, monitor:LVDS-1
workspace=3, monitor:LVDS-1
workspace=4, monitor:LVDS-1
workspace=5, monitor:LVDS-1
workspace=6, monitor:LVDS-1
workspace=7, monitor:LVDS-1
workspace=8, monitor:LVDS-1
workspace=9, monitor:LVDS-1
workspace=10, monitor:LVDS-1


# Default hyprland things
# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen true, match:pin false, no_focus on
# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize
