{
  imports = [
    ./hyprland.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./fastfetch.nix
    ./kitty.nix
    ./swaync.nix
    ./waybar.nix
    ./wofi.nix
    ./wlogout.nix
    ./nvim/default.nix
    ./systemd-units.nix
    ./gtk.nix
    ./qt.nix
    ./git.nix
    ./fish.nix
    ./cursor.nix
  ];
}
